[build.environment]
  NPM_VERSION = "6.14.4"
  HUGO_VERSION = "0.69.0"
  HUGO_ENV = "production"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build:preview"

[[plugins]]
  package = "netlify-plugin-a11y"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
